projection and Manifold Learning

> - [wiki](https://en.wikipedia.org/wiki/Random_projection)

### Projection
Which states that if points in a vector space are of sufficiently high dimension, then they may be projected into a suitable lower-dimensional space in a way which approximately preserves the distances between the points.
> - The original d-dimensional data is projected to a k-dimensional (k << d) subspace $$ X_{k.N}=R_{k.d}.X_{d.N} $$
> - How to choose R: 

$$ m \ge \frac{8.log(k)}{ε^2} $$

SVD???
$$ u.\sum .V^T$$
- duong cheo: cac phan tu co dang aii, ma tran don vi, aii =1 con lai bang 0, ma tran duong cheo ma moi phan tu nam tren duong cheo khac 0, con lai bang o
- ma tran chuyen vi A^t la ma tran co cac dong cua A^T la cac cot cua A, giu nguyen thu tu
- ma tran truc giao A^t.A=I(i la ma tran don vi)
- https://nkvtruong.wordpress.com/2011/10/01/tri-rieng-va-vector-rieng-trong-thong-ke/
- gia tri tuyet doi cua dinh thuc
- Định thức, trong đại số tuyến tính, là một hàm cho mỗi ma trận vuông A, tương ứng với số vô hướng, ký hiệu là det(A). Ý nghĩa hình học của định thức là tỷ lệ xích cho thể tích khi A được coi là một biến đổi tuyến tính. Định thức được sử dụng để giải (và biện luận) các hệ phương trình đại số tuyến tính.
-Từ đây ta có thể suy luận như sau: trong một ma trận vuông, các phần tử nằm trên đường chéo chứa thông tin mô tả thể tích không gian hình hộp tạo bởi các vector của ma trận. Tổng giá trị các phần tử này sẽ phân bố cho các trị riêng, độ lớn của các trị riêng sẽ cho ta biết độ lớn của không gian hình hộp theo hướng của vector riêng tương ứng. Hay nói cách khác, phân bố của dữ liệu mô tả bởi ma trận theo hướng các vector riêng sẽ tỷ lệ với độ lớn của trị riêng tương ứng của nó. Cái này ta có thể thấy rõ qua một số ứng dụng khi xử lý số liệu thống kê như sau:


In [6]:
import numpy as np

data = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [7]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
data_new = data - data.mean(axis = 0)

In [9]:
data_new

array([[-3., -3., -3.],
       [ 0.,  0.,  0.],
       [ 3.,  3.,  3.]])

In [11]:
U, s, V = np.linalg.svd(data_new)

In [12]:
U

array([[-0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ],
       [ 0.70710678,  0.70710678,  0.        ]])

In [13]:
s

array([ 7.34846923,  0.        ,  0.        ])

In [14]:
V

array([[ 0.57735027,  0.57735027,  0.57735027],
       [ 0.        , -0.70710678,  0.70710678],
       [ 0.81649658, -0.40824829, -0.40824829]])

In [15]:
np.linalg.svd?

Signature: np.linalg.svd(a, full_matrices=1, compute_uv=1)
Docstring:
Singular Value Decomposition.

Factors the matrix `a` as ``u * np.diag(s) * v``, where `u` and `v`
are unitary and `s` is a 1-d array of `a`'s singular values.

Parameters
----------
a : (..., M, N) array_like
    A real or complex matrix of shape (`M`, `N`) .
full_matrices : bool, optional
    If True (default), `u` and `v` have the shapes (`M`, `M`) and
    (`N`, `N`), respectively.  Otherwise, the shapes are (`M`, `K`)
    and (`K`, `N`), respectively, where `K` = min(`M`, `N`).
compute_uv : bool, optional
    Whether or not to compute `u` and `v` in addition to `s`.  True
    by default.

Returns
-------
u : { (..., M, M), (..., M, K) } array
    Unitary matrices. The actual shape depends on the value of
    ``full_matrices``. Only returned when ``compute_uv`` is True.
s : (..., K) array
    The singular values for every matrix, sorted in descending order.
v : { (..., N, N), (..., K, N) } array
    Unitary matric

In [16]:
np.diag?

Signature: np.diag(v, k=0)
Docstring:
Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples

In [17]:
from numpy.linalg import inv

In [19]:
A = np.array([[1,2],[3,4]])
A_inv = inv(A)

In [20]:
A_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [21]:
B = A.dot(A_inv)

In [22]:
B

array([[  1.00000000e+00,   0.00000000e+00],
       [  8.88178420e-16,   1.00000000e+00]])